### PR TITLE
Use gender-neutral pronouns

### PR DESCRIPTION
**Pull request by jamiebuilds**
Gender is non-binary.

Fun fact: This is true even if you're talking about sex at a [chromosomal level](https://www.thoughtco.com/sex-chromosome-abnormalities-373286) (which I'm not)

### CODE REVIEW

**Comment by timdorr** [comment]
And hey, if the issues of gender don't speak to you for whatever reason, at the very least, it's also more grammatically-correct.

**Comment by ericcecchi** [comment]
Also on line 304, the question uses the pronoun "he" to describe the anonymous attacker. The documentation should be consistent in both the question and answer.

**Comment by timdorr** [comment]
> Also on line 304, the question uses the pronoun "he" to describe the anonymous attacker. The documentation should be consistent in both the question and answer.

https://github.com/vanhoefm/krackattacks/blob/e0a1269bccaccb4b158abe08bdf4bbd0e11ed5bc/index.html#L304

**Comment by jamiebuilds** [comment]
Fixed as well, thanks @ericcecchi

**Comment by thejameskyle** [comment]
@jaepage your down-votes can't keep us down

**Comment by denysvitali** [comment]
I didn't expect a gender discussion for a WPA2 flaw

**Comment by jamiebuilds** [comment]
It's an easy mistake to make, but luckily the correction is also easy. One press of a green button and we're back on track

**Comment by Mystiflow** [comment]
Really hope this PR gets merged.

**Comment by callmeberzerker** [comment]
Additionally, why have a "man-in-the-middle-attack" in the docs as well? Can't women also attack? Are they incapable of mounting an offensive? Is that what is being suggested here?!

**Comment by jamiebuilds** [comment]
Thank you

**Pull request merged**
