### PR TITLE
Use gender-neutral pronoun

### PR DESCRIPTION
**Pull request by felipecsl**
😄  https://en.wikipedia.org/wiki/Third-person_pronoun

### CODE REVIEW

**Comment by stuntguy3000** [comment]
This has to be a joke.

**Comment by anon82198** [comment]
Honestly. The audacity of this astounds me. Why would you waste somebody's time like that? This is an important project, and you're doing what? You're nitpicking the documentation's choice of wording. I can't believe it, your change doesn't even improve the clarity of the documentation, it just removes an implication about a hypothetical attacker. I'm no better, wasting my time replying to this, but it just makes me so angry that people have such skewed priorities in the current age.

**Comment by vanhoefm** [comment]
Both genders are already taken into account, I'll close to avoid off-topic discussions.

**Comment by felipecsl** [comment]
Whoa the amount of hate on this issue is astounding...
@anon82198 looks like you joined github just to yell at me. 
Indeed doesn't look like a good use of your time

**Comment by stuntguy3000** [comment]
For a damn good reason. This change is stupid, unnecessary and pushing us further down the rabbit hole of "gender equality" rubbish.

**Comment by felipecsl** [comment]
The change was by no means intended to raise any "gender equality" issues at all.
This is all in your mind @stuntguy3000

**Comment by stuntguy3000** [comment]
Why is such a change required? Why can we not use he or she _pronouns_? Do they offend you?

**Pull request closed without merging**
